name: Machine Learning Client CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r machine-learning-client/requirements.txt
          pip install pytest  # Explicitly install pytest

      - name: Run Tests
        run: |
          pytest machine-learning-client/tests

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/machine-learning-client:$IMAGE_TAG -t ${{ secrets.DOCKER_USERNAME }}/machine-learning-client:latest machine-learning-client
          docker push ${{ secrets.DOCKER_USERNAME }}/machine-learning-client:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/machine-learning-client:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: root
          password: ${{ secrets.DO_SERVER_PASSWORD }}
          port: 22
          script: |
            IMAGE_TAG=${{ github.sha }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/machine-learning-client:latest
            docker stop machine-learning-client || true
            docker rm machine-learning-client || true
            docker run -d -p 5002:5002 --name machine-learning-client ${{ secrets.DOCKER_USERNAME }}/machine-learning-client:latest
